import { geoCoordinates } from './geocoordinates.interface';
import { root } from './root.interface';
import { sharepointIds } from './sharepointids.interface';
import { audio } from './audio.interface';
import { deleted } from './deleted.interface';
import { file } from './file.interface';
import { fileSystemInfo } from './filesysteminfo.interface';
import { folder } from './folder.interface';
import { image } from './image.interface';
import { package } from './package.interface';
import { photo } from './photo.interface';
import { publicationFacet } from './publicationfacet.interface';
import { remoteItem } from './remoteitem.interface';
import { shared } from './shared.interface';
import { specialFolder } from './specialfolder.interface';
import { searchResult } from './searchresult.interface';
import { video } from './video.interface';
import { baseItem } from './baseitem.interface';
import { itemAnalytics } from './itemanalytics.interface';
import { listItem } from './listitem.interface';
import { workbook } from './workbook.interface';
import { permission } from './permission.interface';
import { subscription } from './subscription.interface';
import { thumbnailSet } from './thumbnailset.interface';
import { driveItemVersion } from './driveitemversion.interface';

export interface driveItem extends baseItem {
  audio: audio;
  content: any;
  cTag: string;
  deleted: deleted;
  file: file;
  fileSystemInfo: fileSystemInfo;
  folder: folder;
  image: image;
  location: geoCoordinates;
  package: package;
  photo: photo;
  publication: publicationFacet;
  remoteItem: remoteItem;
  root: root;
  searchResult: searchResult;
  shared: shared;
  sharepointIds: sharepointIds;
  size: number;
  specialFolder: specialFolder;
  video: video;
  webDavUrl: string;
  workbook?: workbook;
  analytics?: itemAnalytics;
  children?: driveItem[];
  listItem?: listItem;
  permissions?: permission[];
  subscriptions?: subscription[];
  thumbnails?: thumbnailSet[];
  versions?: driveItemVersion[]
}
