import { assignedLicense } from './assignedlicense.interface';
import { onPremisesProvisioningError } from './onpremisesprovisioningerror.interface';
import { licenseProcessingState } from './licenseprocessingstate.interface';
import { directoryObject } from './directoryobject.interface';
import { calendar } from './calendar.interface';
import { event } from './event.interface';
import { profilePhoto } from './profilephoto.interface';
import { drive } from './drive.interface';
import { extension } from './extension.interface';
import { onenote } from './onenote.interface';
import { groupSetting } from './groupsetting.interface';
import { conversation } from './conversation.interface';
import { conversationThread } from './conversationthread.interface';
import { site } from './site.interface';
import { groupLifecyclePolicy } from './grouplifecyclepolicy.interface';
import { plannerGroup } from './plannergroup.interface';
import { team } from './team.interface';

export interface group extends directoryObject {
  assignedLicenses: assignedLicense[];
  classification: string;
  createdDateTime: Date;
  description: string;
  displayName: string;
  hasMembersWithLicenseErrors: boolean;
  groupTypes: string[];
  licenseProcessingState: licenseProcessingState;
  mail: string;
  mailEnabled: boolean;
  mailNickname: string;
  onPremisesLastSyncDateTime: Date;
  onPremisesProvisioningErrors: onPremisesProvisioningError[];
  onPremisesSecurityIdentifier: string;
  onPremisesSyncEnabled: boolean;
  preferredDataLocation: string;
  proxyAddresses: string[];
  renewedDateTime: Date;
  securityEnabled: boolean;
  visibility: string;
  allowExternalSenders: boolean;
  autoSubscribeNewMembers: boolean;
  isSubscribedByMail: boolean;
  unseenCount: number;
  isArchived: boolean;
  members?: directoryObject[];
  memberOf?: directoryObject[];
  membersWithLicenseErrors?: directoryObject[];
  transitiveMembers?: directoryObject[];
  transitiveMemberOf?: directoryObject[];
  createdOnBehalfOf?: directoryObject;
  owners?: directoryObject[];
  settings?: groupSetting[];
  conversations?: conversation[];
  photos?: profilePhoto[];
  acceptedSenders?: directoryObject[];
  rejectedSenders?: directoryObject[];
  threads?: conversationThread[];
  calendar?: calendar;
  calendarView?: event[];
  events?: event[];
  photo?: profilePhoto;
  drive?: drive;
  drives?: drive[];
  sites?: site[];
  extensions?: extension[];
  groupLifecyclePolicies?: groupLifecyclePolicy[];
  planner?: plannerGroup;
  onenote?: onenote;
  team?: team
}
