import { appListType } from './applisttype.enum';
import { webBrowserCookieSettings } from './webbrowsercookiesettings.enum';
import { ratingAppsType } from './ratingappstype.enum';
import { requiredPasswordType } from './requiredpasswordtype.enum';
import { appListItem } from './applistitem.interface';
import { mediaContentRatingAustralia } from './mediacontentratingaustralia.interface';
import { mediaContentRatingCanada } from './mediacontentratingcanada.interface';
import { mediaContentRatingFrance } from './mediacontentratingfrance.interface';
import { mediaContentRatingGermany } from './mediacontentratinggermany.interface';
import { mediaContentRatingIreland } from './mediacontentratingireland.interface';
import { mediaContentRatingJapan } from './mediacontentratingjapan.interface';
import { mediaContentRatingNewZealand } from './mediacontentratingnewzealand.interface';
import { mediaContentRatingUnitedKingdom } from './mediacontentratingunitedkingdom.interface';
import { mediaContentRatingUnitedStates } from './mediacontentratingunitedstates.interface';
import { iosNetworkUsageRule } from './iosnetworkusagerule.interface';
import { deviceConfiguration } from './deviceconfiguration.interface';

export interface iosGeneralDeviceConfiguration extends deviceConfiguration {
  accountBlockModification: boolean;
  activationLockAllowWhenSupervised: boolean;
  airDropBlocked: boolean;
  airDropForceUnmanagedDropTarget: boolean;
  airPlayForcePairingPasswordForOutgoingRequests: boolean;
  appleWatchBlockPairing: boolean;
  appleWatchForceWristDetection: boolean;
  appleNewsBlocked: boolean;
  appsSingleAppModeList: appListItem[];
  appsVisibilityList: appListItem[];
  appsVisibilityListType: appListType;
  appStoreBlockAutomaticDownloads: boolean;
  appStoreBlocked: boolean;
  appStoreBlockInAppPurchases: boolean;
  appStoreBlockUIAppInstallation: boolean;
  appStoreRequirePassword: boolean;
  bluetoothBlockModification: boolean;
  cameraBlocked: boolean;
  cellularBlockDataRoaming: boolean;
  cellularBlockGlobalBackgroundFetchWhileRoaming: boolean;
  cellularBlockPerAppDataModification: boolean;
  cellularBlockPersonalHotspot: boolean;
  cellularBlockVoiceRoaming: boolean;
  certificatesBlockUntrustedTlsCertificates: boolean;
  classroomAppBlockRemoteScreenObservation: boolean;
  classroomAppForceUnpromptedScreenObservation: boolean;
  compliantAppsList: appListItem[];
  compliantAppListType: appListType;
  configurationProfileBlockChanges: boolean;
  definitionLookupBlocked: boolean;
  deviceBlockEnableRestrictions: boolean;
  deviceBlockEraseContentAndSettings: boolean;
  deviceBlockNameModification: boolean;
  diagnosticDataBlockSubmission: boolean;
  diagnosticDataBlockSubmissionModification: boolean;
  documentsBlockManagedDocumentsInUnmanagedApps: boolean;
  documentsBlockUnmanagedDocumentsInManagedApps: boolean;
  emailInDomainSuffixes: string[];
  enterpriseAppBlockTrust: boolean;
  enterpriseAppBlockTrustModification: boolean;
  faceTimeBlocked: boolean;
  findMyFriendsBlocked: boolean;
  gamingBlockGameCenterFriends: boolean;
  gamingBlockMultiplayer: boolean;
  gameCenterBlocked: boolean;
  hostPairingBlocked: boolean;
  iBooksStoreBlocked: boolean;
  iBooksStoreBlockErotica: boolean;
  iCloudBlockActivityContinuation: boolean;
  iCloudBlockBackup: boolean;
  iCloudBlockDocumentSync: boolean;
  iCloudBlockManagedAppsSync: boolean;
  iCloudBlockPhotoLibrary: boolean;
  iCloudBlockPhotoStreamSync: boolean;
  iCloudBlockSharedPhotoStream: boolean;
  iCloudRequireEncryptedBackup: boolean;
  iTunesBlockExplicitContent: boolean;
  iTunesBlockMusicService: boolean;
  iTunesBlockRadio: boolean;
  keyboardBlockAutoCorrect: boolean;
  keyboardBlockDictation: boolean;
  keyboardBlockPredictive: boolean;
  keyboardBlockShortcuts: boolean;
  keyboardBlockSpellCheck: boolean;
  kioskModeAllowAssistiveSpeak: boolean;
  kioskModeAllowAssistiveTouchSettings: boolean;
  kioskModeAllowAutoLock: boolean;
  kioskModeAllowColorInversionSettings: boolean;
  kioskModeAllowRingerSwitch: boolean;
  kioskModeAllowScreenRotation: boolean;
  kioskModeAllowSleepButton: boolean;
  kioskModeAllowTouchscreen: boolean;
  kioskModeAllowVoiceOverSettings: boolean;
  kioskModeAllowVolumeButtons: boolean;
  kioskModeAllowZoomSettings: boolean;
  kioskModeAppStoreUrl: string;
  kioskModeBuiltInAppId: string;
  kioskModeRequireAssistiveTouch: boolean;
  kioskModeRequireColorInversion: boolean;
  kioskModeRequireMonoAudio: boolean;
  kioskModeRequireVoiceOver: boolean;
  kioskModeRequireZoom: boolean;
  kioskModeManagedAppId: string;
  lockScreenBlockControlCenter: boolean;
  lockScreenBlockNotificationView: boolean;
  lockScreenBlockPassbook: boolean;
  lockScreenBlockTodayView: boolean;
  mediaContentRatingAustralia: mediaContentRatingAustralia;
  mediaContentRatingCanada: mediaContentRatingCanada;
  mediaContentRatingFrance: mediaContentRatingFrance;
  mediaContentRatingGermany: mediaContentRatingGermany;
  mediaContentRatingIreland: mediaContentRatingIreland;
  mediaContentRatingJapan: mediaContentRatingJapan;
  mediaContentRatingNewZealand: mediaContentRatingNewZealand;
  mediaContentRatingUnitedKingdom: mediaContentRatingUnitedKingdom;
  mediaContentRatingUnitedStates: mediaContentRatingUnitedStates;
  networkUsageRules: iosNetworkUsageRule[];
  mediaContentRatingApps: ratingAppsType;
  messagesBlocked: boolean;
  notificationsBlockSettingsModification: boolean;
  passcodeBlockFingerprintUnlock: boolean;
  passcodeBlockFingerprintModification: boolean;
  passcodeBlockModification: boolean;
  passcodeBlockSimple: boolean;
  passcodeExpirationDays: number;
  passcodeMinimumLength: number;
  passcodeMinutesOfInactivityBeforeLock: number;
  passcodeMinutesOfInactivityBeforeScreenTimeout: number;
  passcodeMinimumCharacterSetCount: number;
  passcodePreviousPasscodeBlockCount: number;
  passcodeSignInFailureCountBeforeWipe: number;
  passcodeRequiredType: requiredPasswordType;
  passcodeRequired: boolean;
  podcastsBlocked: boolean;
  safariBlockAutofill: boolean;
  safariBlockJavaScript: boolean;
  safariBlockPopups: boolean;
  safariBlocked: boolean;
  safariCookieSettings: webBrowserCookieSettings;
  safariManagedDomains: string[];
  safariPasswordAutoFillDomains: string[];
  safariRequireFraudWarning: boolean;
  screenCaptureBlocked: boolean;
  siriBlocked: boolean;
  siriBlockedWhenLocked: boolean;
  siriBlockUserGeneratedContent: boolean;
  siriRequireProfanityFilter: boolean;
  spotlightBlockInternetResults: boolean;
  voiceDialingBlocked: boolean;
  wallpaperBlockModification: boolean;
  wiFiConnectOnlyToConfiguredNetworks: boolean
}
