import { managedDeviceOwnerType } from './manageddeviceownertype.enum';
import { complianceState } from './compliancestate.enum';
import { managementAgentType } from './managementagenttype.enum';
import { deviceEnrollmentType } from './deviceenrollmenttype.enum';
import { deviceRegistrationState } from './deviceregistrationstate.enum';
import { deviceManagementExchangeAccessState } from './devicemanagementexchangeaccessstate.enum';
import { deviceManagementExchangeAccessStateReason } from './devicemanagementexchangeaccessstatereason.enum';
import { managedDevicePartnerReportedHealthState } from './manageddevicepartnerreportedhealthstate.enum';
import { deviceActionResult } from './deviceactionresult.interface';
import { configurationManagerClientEnabledFeatures } from './configurationmanagerclientenabledfeatures.interface';
import { deviceHealthAttestationState } from './devicehealthattestationstate.interface';
import { entity } from './entity.interface';
import { deviceCategory } from './devicecategory.interface';
import { deviceConfigurationState } from './deviceconfigurationstate.interface';
import { deviceCompliancePolicyState } from './devicecompliancepolicystate.interface';

export interface managedDevice extends entity {
  userId: string;
  deviceName: string;
  managedDeviceOwnerType: managedDeviceOwnerType;
  deviceActionResults: deviceActionResult[];
  enrolledDateTime: Date;
  lastSyncDateTime: Date;
  operatingSystem: string;
  complianceState: complianceState;
  jailBroken: string;
  managementAgent: managementAgentType;
  osVersion: string;
  easActivated: boolean;
  easDeviceId: string;
  easActivationDateTime: Date;
  azureADRegistered: boolean;
  deviceEnrollmentType: deviceEnrollmentType;
  activationLockBypassCode: string;
  emailAddress: string;
  azureADDeviceId: string;
  deviceRegistrationState: deviceRegistrationState;
  deviceCategoryDisplayName: string;
  isSupervised: boolean;
  exchangeLastSuccessfulSyncDateTime: Date;
  exchangeAccessState: deviceManagementExchangeAccessState;
  exchangeAccessStateReason: deviceManagementExchangeAccessStateReason;
  remoteAssistanceSessionUrl: string;
  remoteAssistanceSessionErrorDetails: string;
  isEncrypted: boolean;
  userPrincipalName: string;
  model: string;
  manufacturer: string;
  imei: string;
  complianceGracePeriodExpirationDateTime: Date;
  serialNumber: string;
  phoneNumber: string;
  androidSecurityPatchLevel: string;
  userDisplayName: string;
  configurationManagerClientEnabledFeatures: configurationManagerClientEnabledFeatures;
  wiFiMacAddress: string;
  deviceHealthAttestationState: deviceHealthAttestationState;
  subscriberCarrier: string;
  meid: string;
  totalStorageSpaceInBytes: number;
  freeStorageSpaceInBytes: number;
  managedDeviceName: string;
  partnerReportedThreatState: managedDevicePartnerReportedHealthState;
  deviceConfigurationStates?: deviceConfigurationState[];
  deviceCompliancePolicyStates?: deviceCompliancePolicyState[];
  deviceCategory?: deviceCategory
}
