import { assignedLicense } from './assignedlicense.interface';
import { assignedPlan } from './assignedplan.interface';
import { licenseAssignmentState } from './licenseassignmentstate.interface';
import { onPremisesExtensionAttributes } from './onpremisesextensionattributes.interface';
import { onPremisesProvisioningError } from './onpremisesprovisioningerror.interface';
import { passwordProfile } from './passwordprofile.interface';
import { provisionedPlan } from './provisionedplan.interface';
import { mailboxSettings } from './mailboxsettings.interface';
import { directoryObject } from './directoryobject.interface';
import { licenseDetails } from './licensedetails.interface';
import { outlookUser } from './outlookuser.interface';
import { message } from './message.interface';
import { mailFolder } from './mailfolder.interface';
import { calendar } from './calendar.interface';
import { calendarGroup } from './calendargroup.interface';
import { event } from './event.interface';
import { person } from './person.interface';
import { contact } from './contact.interface';
import { contactFolder } from './contactfolder.interface';
import { inferenceClassification } from './inferenceclassification.interface';
import { profilePhoto } from './profilephoto.interface';
import { drive } from './drive.interface';
import { extension } from './extension.interface';
import { managedDevice } from './manageddevice.interface';
import { managedAppRegistration } from './managedappregistration.interface';
import { deviceManagementTroubleshootingEvent } from './devicemanagementtroubleshootingevent.interface';
import { plannerUser } from './planneruser.interface';
import { officeGraphInsights } from './officegraphinsights.interface';
import { userSettings } from './usersettings.interface';
import { onenote } from './onenote.interface';
import { userActivity } from './useractivity.interface';
import { onlineMeeting } from './onlinemeeting.interface';
import { group } from './group.interface';

export interface user extends directoryObject {
  accountEnabled: boolean;
  ageGroup: string;
  assignedLicenses: assignedLicense[];
  assignedPlans: assignedPlan[];
  businessPhones: string[];
  city: string;
  companyName: string;
  consentProvidedForMinor: string;
  country: string;
  department: string;
  displayName: string;
  employeeId: string;
  faxNumber: string;
  givenName: string;
  imAddresses: string[];
  isResourceAccount: boolean;
  jobTitle: string;
  legalAgeGroupClassification: string;
  licenseAssignmentStates: licenseAssignmentState[];
  mail: string;
  mailNickname: string;
  mobilePhone: string;
  onPremisesDistinguishedName: string;
  onPremisesExtensionAttributes: onPremisesExtensionAttributes;
  onPremisesImmutableId: string;
  onPremisesLastSyncDateTime: Date;
  onPremisesProvisioningErrors: onPremisesProvisioningError[];
  onPremisesSecurityIdentifier: string;
  onPremisesSyncEnabled: boolean;
  onPremisesDomainName: string;
  onPremisesSamAccountName: string;
  onPremisesUserPrincipalName: string;
  otherMails: string[];
  passwordPolicies: string;
  passwordProfile: passwordProfile;
  officeLocation: string;
  postalCode: string;
  preferredLanguage: string;
  provisionedPlans: provisionedPlan[];
  proxyAddresses: string[];
  showInAddressList: boolean;
  signInSessionsValidFromDateTime: Date;
  state: string;
  streetAddress: string;
  surname: string;
  usageLocation: string;
  userPrincipalName: string;
  userType: string;
  mailboxSettings: mailboxSettings;
  deviceEnrollmentLimit: number;
  aboutMe: string;
  birthday: Date;
  hireDate: Date;
  interests: string[];
  mySite: string;
  pastProjects: string[];
  preferredName: string;
  responsibilities: string[];
  schools: string[];
  skills: string[];
  ownedDevices?: directoryObject[];
  registeredDevices?: directoryObject[];
  manager?: directoryObject;
  directReports?: directoryObject[];
  memberOf?: directoryObject[];
  createdObjects?: directoryObject[];
  ownedObjects?: directoryObject[];
  licenseDetails?: licenseDetails[];
  transitiveMemberOf?: directoryObject[];
  outlook?: outlookUser;
  messages?: message[];
  mailFolders?: mailFolder[];
  calendar?: calendar;
  calendars?: calendar[];
  calendarGroups?: calendarGroup[];
  calendarView?: event[];
  events?: event[];
  people?: person[];
  contacts?: contact[];
  contactFolders?: contactFolder[];
  inferenceClassification?: inferenceClassification;
  photo?: profilePhoto;
  photos?: profilePhoto[];
  drive?: drive;
  drives?: drive[];
  extensions?: extension[];
  managedDevices?: managedDevice[];
  managedAppRegistrations?: managedAppRegistration[];
  deviceManagementTroubleshootingEvents?: deviceManagementTroubleshootingEvent[];
  planner?: plannerUser;
  insights?: officeGraphInsights;
  settings?: userSettings;
  onenote?: onenote;
  activities?: userActivity[];
  onlineMeetings?: onlineMeeting[];
  joinedTeams?: group[]
}
